server:
  port: 7002
spring:
  application:
    name: seckill-service
  redis:
    host: 192.168.81.130
    port: 6379
    password: javacppgorust
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rocketmq_learn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: javacppgorust
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
rocketmq:
  name-server: 192.168.81.130:9876
  consumer:
    group: wly-consumer-group

